# Generated by Django 3.0.6 on 2020-07-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200729_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='video',
            field=models.FileField(upload_to='static/solution-videos/'),
        ),
    ]
